@echo off
REM ****************************************************************************
REM Vivado (TM) v2020.2 (64-bit)
REM
REM Filename    : elaborate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for elaborating the compiled design
REM
REM Generated by Vivado on Sun Nov 20 23:30:20 +0100 2022
REM SW Build 3064766 on Wed Nov 18 09:12:45 MST 2020
REM
REM Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
REM
REM usage: elaborate.bat
REM
REM ****************************************************************************
REM elaborate design
echo "xelab -wto 3517244a06fc4fc3a4d5fab72d9e7be6 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TOP_RISCV_tb_behav xil_defaultlib.TOP_RISCV_tb -log elaborate.log"
call xelab  -wto 3517244a06fc4fc3a4d5fab72d9e7be6 --incr --debug typical --relax --mt 2 -L xil_defaultlib -L secureip --snapshot TOP_RISCV_tb_behav xil_defaultlib.TOP_RISCV_tb -log elaborate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
